Change end location of .next/static
infinum/js-pipeline pull request #7
Opened 2022-12-08 13:09 UTC by kristian240

https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files

2022-12-08 13:21 UTC, DarkoKukovec approved these changes

2022-12-08 14:04 UTC, isBatak requested changes

2022-12-08 14:04 UTC, isBatak commented on .github/workflows/pipeline.yml
>            mv ./.next/standalone/server.js ./.next/standalone/index.js;
@mislavk mentioned that we should remove `;` from all the lines.

2022-12-09 07:26 UTC, kristian240 reviewed
Remove ; from end of lines

2022-12-09 07:27 UTC, isBatak approved these changes

2022-12-09 09:01 UTC, merged